### ISSUE TITLE
M3U from URL

### ISSUE THREAD

**Issue by TopperBG** [hagaygo/tvheadendm3usync#2]
M3U file could be URL like example [Fluxus.tv](https://pastebin.com/raw/hfRRAcpy) as many IPTV providers works.
Is it easy to be implemented ?
The above URL was saved as local .M3U file and network Fluxus.tv was created very fast with 5079 muxes but not continue to scan and map services - is that behaviour by purpose ?

**Comment by hagaygo** [comment]
only file is supported.

The reason as stated on the readme file is to be able to link the m3u URL entry to a specific tvh service/mux (by changing the m3u file to have tvheadend uuid on the entry).

Working with URL is not gonna be much more beneficial than tvheadend's built-in m3u url fetch since we can  not really update the remote m3u file and a local file.

After initial import you gonna have to manually add new services to the local m3u file or update current url in case of a url change.

Just saw your second question , yes , its on purpose for newly created network (also it set to 1 simultaneous stream  for that network).
You gonna have to trigger the scan manually for a newly created network.
